<?php

use App\Http\Controllers\Api\AccountSettingsController;
use App\Http\Controllers\Api\AdminController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ClientProfileController;
use App\Http\Controllers\Api\ContractController;
use App\Http\Controllers\Api\ContractReviewController;
use App\Http\Controllers\Api\ContractSupportRequestController;
use App\Http\Controllers\Api\ContractScopeChangeController;
use App\Http\Controllers\Api\ConversationController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\EmailVerificationController;
use App\Http\Controllers\Api\FreelancerProfileController;
use App\Http\Controllers\Api\FreelancerInviteController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\FreelancerResumeController;
use App\Http\Controllers\Api\JobController;
use App\Http\Controllers\Api\MarketplaceNotificationController;
use App\Http\Controllers\Api\NotificationPreferenceController;
use App\Http\Controllers\Api\MarketplaceSearchController;
use App\Http\Controllers\Api\MarketplaceSaveController;
use App\Http\Controllers\Api\MarketplaceSavedSearchController;
use App\Http\Controllers\Api\MarketplaceReportController;
use App\Http\Controllers\Api\MarketplaceReliabilityController;
use App\Http\Controllers\Api\MilestoneSubmissionController;
use App\Http\Controllers\Api\PortfolioController;
use App\Http\Controllers\Api\PasswordController;
use App\Http\Controllers\Api\PasswordResetController;
use App\Http\Controllers\Api\ProfilePhotoController;
use App\Http\Controllers\Api\ProposalController;
use App\Http\Controllers\Api\ProposalOfferController;
use App\Http\Controllers\Api\ProposalCreditController;
use App\Http\Controllers\Api\PublicFreelancerController;
use App\Http\Controllers\Api\RealtimeConfigController;
use App\Http\Controllers\Api\VerificationRequestController;
use Illuminate\Support\Facades\Route;

Route::get('/health', [HealthController::class, 'show']);

Route::post('/auth/register', [AuthController::class, 'register'])->middleware('throttle:6,1');
Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:10,1');
Route::post('/auth/google', [AuthController::class, 'google'])->middleware('throttle:10,1');
Route::post('/admin/auth/login', [AuthController::class, 'adminLogin'])->middleware('throttle:6,1');
Route::post('/auth/forgot-password', [PasswordResetController::class, 'send'])->middleware('throttle:6,1');
Route::post('/auth/reset-password', [PasswordResetController::class, 'reset'])->middleware('throttle:6,1');
Route::get('/email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware('signed')->name('verification.verify');

Route::get('/jobs', [JobController::class, 'index']);

Route::middleware(['auth:sanctum', 'account.active'])->group(function () {
    Route::get('/auth/user', [AuthController::class, 'user']);
    Route::get('/realtime/config', [RealtimeConfigController::class, 'show']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::post('/email/verification-notification', [EmailVerificationController::class, 'send'])->middleware('throttle:6,1');
    Route::post('/auth/roles', [AuthController::class, 'addRole']);
    Route::patch('/auth/active-role', [AuthController::class, 'setActiveRole']);
    Route::get('/account-settings', [AccountSettingsController::class, 'show']);
    Route::put('/account-settings', [AccountSettingsController::class, 'update']);
    Route::post('/verification-requests', [VerificationRequestController::class, 'request'])->middleware('throttle:5,1');
    Route::put('/account/password', [PasswordController::class, 'update']);

    Route::get('/dashboard', [DashboardController::class, 'show']);
    Route::get('/proposal-credits', [ProposalCreditController::class, 'show']);
    Route::get('/reliability', [MarketplaceReliabilityController::class, 'show']);
    Route::get('/search', [MarketplaceSearchController::class, 'search']);
    Route::post('/reports', [MarketplaceReportController::class, 'store'])->middleware('throttle:10,1');
    Route::get('/marketplace-saves', [MarketplaceSaveController::class, 'index']);
    Route::put('/saved-jobs/{job}', [MarketplaceSaveController::class, 'saveJob']);
    Route::delete('/saved-jobs/{job}', [MarketplaceSaveController::class, 'removeJob']);
    Route::put('/saved-talent/{freelancerProfile}', [MarketplaceSaveController::class, 'saveTalent']);
    Route::delete('/saved-talent/{freelancerProfile}', [MarketplaceSaveController::class, 'removeTalent']);
    Route::get('/marketplace-saved-searches', [MarketplaceSavedSearchController::class, 'index']);
    Route::post('/marketplace-saved-searches', [MarketplaceSavedSearchController::class, 'store']);
    Route::patch('/marketplace-saved-searches/{savedSearch}', [MarketplaceSavedSearchController::class, 'update']);
    Route::delete('/marketplace-saved-searches/{savedSearch}', [MarketplaceSavedSearchController::class, 'destroy']);
    Route::prefix('admin')->middleware('ability:admin')->group(function () {
        Route::get('/dashboard', [AdminController::class, 'dashboard']);
        Route::get('/users', [AdminController::class, 'users']);
        Route::patch('/users/{user}', [AdminController::class, 'updateUser']);
        Route::get('/jobs', [AdminController::class, 'jobs']);
        Route::patch('/jobs/{job}', [AdminController::class, 'updateJob']);
        Route::get('/reports', [AdminController::class, 'reports']);
        Route::patch('/reports/{report}', [AdminController::class, 'updateReport']);
        Route::get('/support-requests', [AdminController::class, 'supportRequests']);
        Route::patch('/support-requests/{supportRequest}', [AdminController::class, 'updateSupportRequest']);
        Route::get('/payment-records', [AdminController::class, 'paymentRecords']);
        Route::get('/audit-logs', [AdminController::class, 'auditLogs']);
        Route::get('/verifications', [AdminController::class, 'verifications']);
        Route::get('/reliability', [AdminController::class, 'reliability']);
        Route::patch('/reliability-events/{reliabilityEvent}', [AdminController::class, 'updateReliabilityEvent']);
        Route::get('/identity-verification-submissions/{identityVerificationSubmission}/documents/{side}', [AdminController::class, 'downloadIdentityVerificationDocument']);
        Route::patch('/users/{user}/identity-verification', [AdminController::class, 'updateIdentityVerification']);
        Route::patch('/client-profiles/{clientProfile}/company-verification', [AdminController::class, 'updateCompanyVerification']);
        Route::patch('/contracts/{contract}/payment-hold', [AdminController::class, 'updatePaymentHold']);
    });
    Route::get('/notifications', [MarketplaceNotificationController::class, 'index']);
    Route::get('/notification-preferences', [NotificationPreferenceController::class, 'show']);
    Route::put('/notification-preferences', [NotificationPreferenceController::class, 'update']);
    Route::get('/notifications/summary', [MarketplaceNotificationController::class, 'summary']);
    Route::patch('/notifications/read-all', [MarketplaceNotificationController::class, 'markAllRead']);
    Route::patch('/notifications/{notification}/read', [MarketplaceNotificationController::class, 'markRead']);
    Route::get('/conversations', [ConversationController::class, 'index']);
    Route::get('/conversations/summary', [ConversationController::class, 'summary']);
    Route::get('/conversations/startable-proposals', [ConversationController::class, 'startableProposals']);
    Route::get('/conversations/{conversation}', [ConversationController::class, 'show']);
    Route::post('/conversations/{conversation}/messages', [ConversationController::class, 'storeMessage'])->middleware('throttle:60,1');
    Route::get('/conversation-message-files/{file}/download', [ConversationController::class, 'downloadFile']);
    Route::get('/contracts', [ContractController::class, 'index']);
    Route::get('/contracts/{contract}', [ContractController::class, 'show']);
    Route::post('/contracts/{contract}/milestones', [ContractController::class, 'storeMilestone']);
    Route::patch('/milestones/{milestone}', [ContractController::class, 'updateMilestone']);
    Route::post('/milestones/{milestone}/submissions', [MilestoneSubmissionController::class, 'store'])->middleware('throttle:20,1');
    Route::get('/milestone-submission-files/{file}/download', [MilestoneSubmissionController::class, 'download']);
    Route::post('/contracts/{contract}/request-completion', [ContractController::class, 'requestCompletion']);
    Route::post('/contracts/{contract}/complete', [ContractController::class, 'complete']);
    Route::post('/contracts/{contract}/close', [ContractController::class, 'close']);
    Route::post('/contracts/{contract}/reviews', [ContractReviewController::class, 'store']);
    Route::post('/contracts/{contract}/support-requests', [ContractSupportRequestController::class, 'store']);
    Route::post('/contracts/{contract}/scope-changes', [ContractScopeChangeController::class, 'store']);
    Route::patch('/contract-scope-changes/{scopeChange}', [ContractScopeChangeController::class, 'update']);
    Route::get('/freelancer-profile', [FreelancerProfileController::class, 'show']);
    Route::put('/freelancer-profile', [FreelancerProfileController::class, 'update']);
    Route::get('/client-profile', [ClientProfileController::class, 'show']);
    Route::put('/client-profile', [ClientProfileController::class, 'update']);
    Route::post('/portfolio-items', [PortfolioController::class, 'store']);
    Route::patch('/portfolio-items/{portfolioItem}', [PortfolioController::class, 'update']);
    Route::delete('/portfolio-items/{portfolioItem}', [PortfolioController::class, 'destroy']);
    Route::post('/freelancer-resume', [FreelancerResumeController::class, 'store'])->middleware('throttle:10,1');
    Route::delete('/freelancer-resume', [FreelancerResumeController::class, 'destroy']);
    Route::post('/profile-photo', [ProfilePhotoController::class, 'store'])->middleware('throttle:10,1');
    Route::get('/jobs/mine', [JobController::class, 'mine']);
    Route::post('/jobs', [JobController::class, 'store']);
    Route::patch('/jobs/{job}', [JobController::class, 'update']);
    Route::post('/jobs/{job}/invites', [FreelancerInviteController::class, 'store']);
    Route::get('/freelancer-invites', [FreelancerInviteController::class, 'index']);
    Route::patch('/freelancer-invites/{invite}', [FreelancerInviteController::class, 'update']);

    Route::post('/jobs/{job}/proposals', [ProposalController::class, 'store'])->middleware('throttle:20,1');
    Route::get('/jobs/{job}/my-proposal', [ProposalController::class, 'mineForJob']);
    Route::get('/jobs/{job}/proposals', [ProposalController::class, 'forJob']);
    Route::get('/proposals/mine', [ProposalController::class, 'mine']);
    Route::patch('/proposals/{proposal}', [ProposalController::class, 'updateStatus']);
    Route::post('/proposals/{proposal}/offers', [ProposalOfferController::class, 'store']);
    Route::patch('/proposal-offers/{offer}', [ProposalOfferController::class, 'update']);
    Route::post('/proposals/{proposal}/conversation', [ConversationController::class, 'startFromProposal']);
    Route::get('/proposals/{proposal}/resume', [FreelancerResumeController::class, 'downloadProposalResume']);
});

Route::get('/jobs/{job}', [JobController::class, 'show']);
Route::get('/freelancers/{user}', [PublicFreelancerController::class, 'show']);
