import { useEffect, useState } from 'react'
import { Link, useNavigate, useOutletContext } from 'react-router-dom'
import { useDispatch } from 'react-redux'
import api from '../services/api'
import { setApiStatus } from '../redux/slices/appSlice'
import { usePreferences } from '../contexts/PreferencesContext'

const categories = [['⌘', 'Development & IT'], ['✎', 'Design & Creative'], ['◉', 'Sales & Marketing'], ['✦', 'Writing & Translation'], ['◌', 'Admin Support'], ['▦', 'Finance & Accounting']]
const jobs = [
  ['UI/UX Designer for Mobile App', 'Figma · UI Design · Mobile Design', 'Ks 600,000 – Ks 900,000', '4.9', '21 reviews'],
  ['WordPress Developer for Business Website', 'WordPress · PHP · Elementor · CSS', 'Ks 450,000 – Ks 700,000', '4.8', '18 reviews'],
  ['Content Writer — Blog Articles (Tech)', 'Content Writing · SEO · Research', 'Ks 120,000 – Ks 200,000', '4.9', '32 reviews'],
]
const proposals = [
  ['Nandar Win', 'Product Designer', 'Figma · UI/UX · Prototyping', 'Ks 450,000', '4.9 (28)'],
  ['Zaw Min Htet', 'React Developer', 'React · TypeScript · Tailwind CSS', 'Ks 900,000', '4.8 (34)'],
  ['Su Myat Thu', 'Social Media Manager', 'Content Plan · Canva · Copywriting', 'Ks 300,000', '4.7 (19)'],
]

function Badge({ children }) { return <span className="tag">{children}</span> }
function Stars({ text }) { return <span className="rating">★ {text}</span> }
function Avatar({ name, color = 'purple' }) { return <span className={`avatar ${color}`}>{name.split(' ').map(part => part[0]).slice(0, 2).join('')}</span> }

function HomePage() {
  const dispatch = useDispatch()
  const { language } = usePreferences()
  useEffect(() => { api.get('/health').then(() => dispatch(setApiStatus('connected'))).catch(() => dispatch(setApiStatus('offline'))) }, [dispatch])
  const copy = language === 'my'
    ? { eyebrow: 'မြန်မာနိုင်ငံအတွက် Freelance Marketplace', title: 'မြန်မာ Talent. ကမ္ဘာ့အခွင့်အလမ်း.', body: 'လုပ်ငန်းများနှင့် ကျွမ်းကျင်သူများကို ယုံကြည်စိတ်ချစွာ ချိတ်ဆက်ပေးပါသည်။', work: 'အလုပ်ရှာမည်', hire: 'Talent ရှာမည်' }
    : { eyebrow: 'Myanmar freelance marketplace', title: 'Myanmar talent. Global opportunity.', body: 'TalentXpanse connects ambitious businesses with skilled Myanmar professionals — and helps independent talent find meaningful work.', work: 'Find work', hire: 'Hire talent' }
  return <>
    <section className="home-hero"><div className="hero-copy"><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p>{copy.body}</p><div className="hero-actions"><Link to="/register" className="button button-primary">{copy.work}</Link><Link to="/register" className="button button-outline">{copy.hire}</Link></div></div>
      <div className="hero-art"><div className="orb orb-one" /><div className="orb orb-two" /><div className="profile-float"><Avatar name="May Thiri" /><div><b>Top Rated Freelancer</b><small>★★★★★ &nbsp; 100% Job Success</small></div></div><div className="project-float"><span className="float-icon">▣</span><b>Website redesign</b><small>Budget &nbsp; Ks 800,000</small><div><Badge>React</Badge><Badge>UI/UX</Badge></div></div><div className="hero-person">✦</div></div>
    </section>
    <section className="category-section"><div className="section-heading"><div><p className="eyebrow">Explore opportunities</p><h2>Work that matches your expertise</h2></div><Link to="/jobs">Browse all jobs →</Link></div><div className="category-grid">{categories.map(([icon, label]) => <Link key={label} to="/jobs" className="category-card"><span>{icon}</span>{label}</Link>)}</div></section>
    <section className="trust-row"><div><span>✓</span><b>Verified profiles</b><small>Reviewed for trust and quality.</small></div><div><span>▣</span><b>Secure payments</b><small>Pay only when work is approved.</small></div><div><span>◌</span><b>Local language support</b><small>Use TalentXpanse in English or Myanmar.</small></div></section>
    <section className="audience-section"><article><div className="audience-icon">✦</div><div><p className="eyebrow">For freelancers</p><h2>Build work around your life.</h2><p>Showcase your skills, find projects that fit, and work with clients anywhere.</p><ul><li>Create a professional profile</li><li>Receive relevant job matches</li><li>Get paid securely in MMK</li></ul><Link to="/register">Start your journey →</Link></div></article><article><div className="audience-icon">⌘</div><div><p className="eyebrow">For clients</p><h2>Find people who move work forward.</h2><p>Post a job, compare proposals, and build a trusted team for any project.</p><ul><li>Post a job in minutes</li><li>Review skills and portfolios</li><li>Manage contracts in one place</li></ul><Link to="/register">Post a job →</Link></div></article></section>
  </>
}

function AuthPage({ mode }) {
  const navigate = useNavigate()
  const [role, setRole] = useState('freelancer')
  return <section className="auth-page"><div className="auth-panel"><Link className="brand auth-brand" to="/">Talent<span>Xpanse</span></Link><div className="auth-card"><p className="eyebrow">{mode === 'login' ? 'Welcome back' : 'Create your account'}</p><h1>{mode === 'login' ? 'Continue your journey.' : 'How would you like to use TalentXpanse?'}</h1><p className="auth-intro">{mode === 'login' ? 'Sign in to manage your work and opportunities.' : 'Start with one path today. You can add the other profile later.'}</p>
    {mode === 'register' && <div className="role-cards"><button className={role === 'freelancer' ? 'selected' : ''} onClick={() => setRole('freelancer')}><span>✦</span><div><b>Find work</b><small>Build your profile, discover projects, and send proposals.</small></div><i /></button><button className={role === 'client' ? 'selected' : ''} onClick={() => setRole('client')}><span>⌘</span><div><b>Hire talent</b><small>Post a job, discover skilled people, and hire with confidence.</small></div><i /></button></div>}
    {mode === 'login' && <div className="auth-fields"><label>Email<input type="email" placeholder="you@example.com" /></label><label>Password<input type="password" placeholder="••••••••" /></label></div>}
    <button className="button button-primary auth-continue" onClick={() => navigate(`/dashboard?role=${role}`)}>{mode === 'login' ? 'Log in' : 'Continue'}</button><div className="auth-divider"><span>or sign up with</span></div><div className="social-buttons"><button><b className="google-mark">G</b>Continue with Google</button><button><b>●</b>Continue with Apple</button></div><p className="auth-switch">{mode === 'login' ? 'New to TalentXpanse?' : 'Already have an account?'} <Link to={mode === 'login' ? '/register' : '/login'}>{mode === 'login' ? 'Sign up' : 'Log in'}</Link></p>
  </div></div><aside className="auth-art"><div className="art-card large"><span>▣</span><b>Projects that matter</b><small>Find the right people and the right work.</small></div><div className="art-card small"><Avatar name="Nandar Win" /><b>Build lasting relationships.</b></div><div className="art-figure">⌘</div></aside></section>
}

function Metric({ icon, label, value, note }) { return <article className="metric"><span>{icon}</span><div><small>{label}</small><b>{value}</b><em>{note}</em></div></article> }

function ClientDashboard() { return <div className="dashboard-content"><header className="dashboard-header"><div><p className="eyebrow">Client workspace</p><h1>Good morning, Aye Chan</h1><p>Here’s what’s happening with your projects today.</p></div><button className="button button-primary">⊕ Post a job</button></header><section className="metrics"><Metric icon="▣" label="Open jobs" value="3" note="Ks 2,190,000 budget" /><Metric icon="▤" label="New proposals" value="12" note="Review proposals →" /><Metric icon="◎" label="Shortlisted" value="5" note="Across 4 jobs" /><Metric icon="▧" label="Active contracts" value="2" note="Ks 1,240,000 in progress" /></section><section className="dashboard-grid"><article className="panel proposal-panel"><div className="panel-title"><h2>Proposals to review <span>12</span></h2><a>View all</a></div>{proposals.map(([name, job, skills, amount, rating]) => <div className="proposal-row" key={name}><Avatar name={name} color={name === 'Zaw Min Htet' ? 'blue' : 'purple'} /><div className="proposal-person"><b>{name}</b><small>{job}</small><Stars text={rating} /><div>{skills.split(' · ').map(skill => <Badge key={skill}>{skill}</Badge>)}</div></div><div className="proposal-amount"><b>{amount}</b><small>Fixed price</small></div><button>Review proposal</button></div>)}</article><article className="panel jobs-panel"><div className="panel-title"><h2>Your open jobs</h2><a>View all</a></div>{[['⌘', 'Product Designer', 'Ks 400,000 – Ks 600,000', '7 proposals'], ['</>', 'React Developer', 'Ks 800,000 – Ks 1,200,000', '12 proposals'], ['◉', 'Social Media Manager', 'Ks 250,000 – Ks 400,000', '5 proposals']].map(([icon, title, budget, count]) => <div className="open-job" key={title}><span>{icon}</span><div><b>{title}</b><small>{budget} · Fixed price</small><em>{count}</em></div><i>›</i></div>)}</article></section><section className="panel recommendations"><div className="panel-title"><h2>Recommended talent for you</h2><a>View all talent</a></div><div className="talent-grid">{[['Kyaw Phyoe','Full Stack Developer','Ks 25,000/hr','React · Node.js'],['May Htet','UI/UX Designer','Ks 20,000/hr','Figma · Prototyping'],['Thida Tun','Video Editor','Ks 18,000/hr','Premiere Pro · DaVinci'],['Zin Linn','Digital Marketer','Ks 15,000/hr','SEO · Facebook Ads']].map(([name,title,rate,skills]) => <article key={name}><Avatar name={name} /><b>{name}</b><small>{title}</small><Stars text="4.8" /><div>{skills.split(' · ').map(s => <Badge key={s}>{s}</Badge>)}</div><strong>{rate}</strong><em>● Available</em></article>)}</div></section></div> }

function FreelancerDashboard() { return <div className="dashboard-content"><header className="dashboard-header"><div><p className="eyebrow">Freelancer workspace</p><h1>Good morning, Thinzar ☀</h1><p>Here’s what’s happening with your freelance journey today.</p></div><button className="button button-outline">✎ Edit profile</button></header><section className="profile-strength"><div className="progress-ring"><span>80<small>%</small></span></div><div><h2>Profile strength: <em>Strong</em></h2><p>Complete the remaining steps to boost visibility and win more projects.</p></div><div className="strength-actions"><button>▣ Add portfolio</button><button>◷ Set availability</button><button>♢ Verify identity</button></div></section><section className="metrics"><Metric icon="▣" label="Job matches" value="24" note="↑ 6 new" /><Metric icon="▤" label="Active proposals" value="6" note="View all →" /><Metric icon="◎" label="Interviews" value="2" note="View all →" /><Metric icon="₭" label="This month" value="Ks 1,240,000" note="↑ 18% vs last month" /></section><section className="freelancer-grid"><article className="jobs-picked"><div className="panel-title"><h2>Jobs picked for you</h2><a>View all jobs →</a></div>{jobs.map(([title, skills, budget, rating, reviews], index) => <article className="picked-job" key={title}><span className={`job-icon icon-${index}`}>{index === 0 ? '✎' : index === 1 ? '</>' : '✦'}</span><div><b>{title}</b><small>Client rating <Stars text={`${rating} · ${reviews}`} /></small><div>{skills.split(' · ').map(skill => <Badge key={skill}>{skill}</Badge>)}</div></div><div className="job-budget"><b>{budget}</b><small>Fixed price</small></div><button>Submit proposal</button></article>)}</article><aside><article className="panel activity"><div className="panel-title"><h2>Proposal activity</h2><a>View all</a></div>{[['➤','Proposal submitted','UI/UX Designer for Mobile App','2h ago'],['●','Client replied','WordPress Developer for Business Website','5h ago'],['◷','Interview scheduled','E-commerce Website Redesign','1d ago'],['◌','Proposal viewed','Social Media Manager','2d ago']].map(([icon,title,sub,time]) => <div key={title}><span>{icon}</span><section><b>{title}</b><small>{sub}</small></section><em>{time}</em></div>)}</article><article className="panel earnings"><div className="panel-title"><h2>Earnings overview</h2><button>This month⌄</button></div><b>Ks 1,240,000</b><em>↑ 18% vs last month</em><div className="bars">{[28, 45, 73, 66, 100].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><a>View full earnings →</a></article></aside></section></div> }

function DashboardPage() { const { role } = useOutletContext(); return role === 'freelancer' ? <FreelancerDashboard /> : <ClientDashboard /> }

function SimplePage({ name }) { const messages = { 'Find Jobs': ['Find work', 'Your personalized job feed will be available here.'], 'Job Detail': ['Job details', 'Review the project scope and send a proposal.'], Profile: ['Your profile', 'Build a profile clients can trust.'], About: ['Made for ambitious work', 'TalentXpanse connects Myanmar talent to meaningful opportunities.'], Contact: ['Get in touch', 'Our marketplace team is here to help.'] }; const [title, body] = messages[name] || ['TalentXpanse', 'This page is on the way.']; return <section className="simple-page"><p className="eyebrow">TalentXpanse</p><h1>{title}</h1><p>{body}</p><Link to="/" className="button button-primary">Back home</Link></section> }

export default function Page({ name }) { if (name === 'Home') return <HomePage />; if (name === 'Login') return <AuthPage mode="login" />; if (name === 'Register') return <AuthPage mode="register" />; if (name === 'Dashboard') return <DashboardPage />; return <SimplePage name={name} /> }
