import { Link } from 'react-router-dom'
import { usePreferences } from '../contexts/PreferencesContext'
import '../public-pages.css'

const categories = ['Development & IT', 'Design & Creative', 'Sales & Marketing', 'Writing & Translation', 'Admin Support', 'Finance & Accounting']

function HomePage() {
  const { language } = usePreferences()
  const isMyanmar = language === 'my'
  const copy = isMyanmar
    ? { eyebrow: 'မြန်မာ အလွတ်တန်း အလုပ်ဈေးကွက်', title: 'မြန်မာအရည်အချင်း။ အခွင့်အလမ်းအသစ်။', body: 'TalentXpanse က လုပ်ငန်းများနှင့် မြန်မာအလွတ်တန်းပညာရှင်များကို လုံခြုံစွာ ချိတ်ဆက်ပေးပါသည်။', find: 'အလုပ်များ ရှာဖွေမည်', hire: 'ပညာရှင် ရှာဖွေမည်', explore: 'အခွင့်အလမ်းများ', heading: 'သင့်ကျွမ်းကျင်မှုနှင့် ကိုက်ညီသော အလုပ်များ', how: 'ဘယ်လိုအလုပ်လုပ်သလဲ' }
    : { eyebrow: 'Myanmar freelance marketplace', title: 'Myanmar talent. Meaningful opportunity.', body: 'TalentXpanse connects businesses with skilled Myanmar professionals — and gives independent talent a clear way to find great work.', find: 'Find freelance jobs', hire: 'Hire freelancers', explore: 'Explore opportunities', heading: 'Work that matches your expertise', how: 'How it works' }
  return <><section className="home-hero"><div className="hero-copy"><p className="eyebrow">{copy.eyebrow}</p><h1>{copy.title}</h1><p>{copy.body}</p><div className="hero-actions"><Link to="/jobs" className="button button-primary">{copy.find}</Link><Link to="/register?role=client" className="button button-outline">{copy.hire}</Link></div><Link className="hero-how" to="/how-it-works">{copy.how} →</Link></div><div className="hero-art"><div className="orb orb-one" /><div className="orb orb-two" /><div className="profile-float"><span className="float-icon">★</span><div><b>Trusted freelancers</b><small>Profiles, work history, and clear reviews.</small></div></div><div className="project-float"><span className="float-icon">▣</span><b>Website redesign</b><small>Milestones · messages · delivery</small><div><span className="tag">React</span><span className="tag">UI/UX</span></div></div><div className="hero-person">✦</div></div></section><section className="category-section"><div className="section-heading"><div><p className="eyebrow">{copy.explore}</p><h2>{copy.heading}</h2></div><Link to="/jobs">Browse all jobs →</Link></div><div className="category-grid">{categories.map((label, index) => <Link key={label} to="/jobs" className="category-card"><span>{['</>','✦','↗','✎','▤','₭'][index]}</span>{label}</Link>)}</div></section><section className="trust-row"><div><span>✓</span><b>Trusted profiles</b><small>Real work history and double-sided reviews.</small></div><div><span>▣</span><b>Clear delivery</b><small>Milestones keep every project on track.</small></div><div><span>文</span><b>English and Myanmar</b><small>Use the marketplace in the language you prefer.</small></div></section></>
}

function HowItWorks() {
  return <section className="how-page"><header><p className="eyebrow">How TalentXpanse works</p><h1>A clear process for better freelance work.</h1><p>Start with the role you need today. You can add the other workspace later.</p></header><div className="how-grid"><article><p className="eyebrow">For freelancers</p><h2>Find and deliver great work.</h2><ol><li>Create a focused profile, portfolio, and optional CV.</li><li>Search jobs and spend Proposal Credits only on work you want.</li><li>Message clients, agree milestones, submit work, and build your review history.</li></ol><Link className="button button-primary" to="/register?role=freelancer">Find freelance jobs</Link></article><article><p className="eyebrow">For clients</p><h2>Hire with confidence.</h2><ol><li>Create a company workspace and post a clear job.</li><li>Review proposals, portfolios, trust history, and communicate before hiring.</li><li>Manage milestones, approve delivery, and leave a fair review.</li></ol><Link className="button button-outline" to="/register?role=client">Hire freelancers</Link></article></div><section className="how-note"><b>Payments are not yet live.</b><span>TalentXpanse currently tracks project delivery. Payment collection and payouts will be added through a compliant payment partner later.</span></section></section>
}

function SimplePage({ name }) { const text = name === 'About' ? ['Built for ambitious work', 'TalentXpanse is a Myanmar-first freelance marketplace designed around clarity, trust, and real project delivery.'] : ['Contact', 'Our marketplace support experience is being prepared.']; return <section className="simple-page"><p className="eyebrow">TalentXpanse</p><h1>{text[0]}</h1><p>{text[1]}</p><Link to="/" className="button button-primary">Back home</Link></section> }
export default function Page({ name }) { if (name === 'Home') return <HomePage />; if (name === 'HowItWorks') return <HowItWorks />; return <SimplePage name={name} /> }
